/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import classes.Author;
import classes.Copy;
import static classes.Copy.CopyState.BORROWED;
import static classes.Copy.CopyState.STORED;
import classes.CopyDAL;
import classes.Member;
import classes.MemberDAL;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author berik
 */
public class LibraryMain extends javax.swing.JFrame {

    /**
     * Creates new form LibraryMain
     */
    public LibraryMain() {
        genModelCopies();
        genMembers();
        initComponents();
    }
enum SwitchPanel{BORROW,PREFERENCES;}
    private void genModelCopies() {
        CopyDAL objCopyDAL = new CopyDAL();
        listCopies = objCopyDAL.getCopies();

        for (int i = 0; i < listCopies.size(); i++) {
            modelCopies.addElement(listCopies.get(i));
        }
    }
    
        private void genMembers() {
        MemberDAL objMemberDAL = new MemberDAL();
        listMembers = objMemberDAL.getMembers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupFilterState = new javax.swing.ButtonGroup();
        bGroupFilterTAI = new javax.swing.ButtonGroup();
        mainJTabbedPanel = new javax.swing.JTabbedPane();
        welcomePanel = new javax.swing.JPanel();
        searchAndBorrow = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCopies = new javax.swing.JList();
        jPanelCopyInfo = new javax.swing.JPanel();
        lblBookTitle = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lvlISBN = new javax.swing.JLabel();
        lblBookISBN = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblBookType = new javax.swing.JLabel();
        lblBookEditorial = new javax.swing.JLabel();
        lblEditorial = new javax.swing.JLabel();
        lblBookEdition = new javax.swing.JLabel();
        lblEdition1 = new javax.swing.JLabel();
        lblBookState = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCopyCode = new javax.swing.JLabel();
        lblBookCopyCode = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAuthors = new javax.swing.JList();
        jButtonBorrowRequest = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldSearch = new javax.swing.JTextField();
        jRadioAll = new javax.swing.JRadioButton();
        jRadioStored = new javax.swing.JRadioButton();
        jRadioByTitle = new javax.swing.JRadioButton();
        jRadioByAuthor = new javax.swing.JRadioButton();
        jRadioByISBN = new javax.swing.JRadioButton();
        loginPanel = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        jTabbedPaneLogin = new javax.swing.JTabbedPane();
        jPanelLogin = new javax.swing.JPanel();
        jTextFieldUser = new javax.swing.JTextField();
        lblPWD = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jTextFieldPWD = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        lblWrongUPWD = new javax.swing.JLabel();
        borrowPanel = new javax.swing.JPanel();
        jButtonBackFromBorrow = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainJTabbedPanel.setBackground(new java.awt.Color(102, 102, 102));
        mainJTabbedPanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        mainJTabbedPanel.setMinimumSize(new java.awt.Dimension(1024, 600));
        mainJTabbedPanel.setSize(new java.awt.Dimension(1024, 600));

        org.jdesktop.layout.GroupLayout welcomePanelLayout = new org.jdesktop.layout.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1007, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 575, Short.MAX_VALUE)
        );

        mainJTabbedPanel.addTab("                              Portada                              ", welcomePanel);

        searchAndBorrow.setLayout(new java.awt.CardLayout());

        searchPanel.setBackground(new java.awt.Color(230, 230, 230));
        searchPanel.setFocusable(false);

        jListCopies.setModel(modelCopies);
        jListCopies.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                displayItem(evt);
            }
        });
        jScrollPane1.setViewportView(jListCopies);

        jPanelCopyInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de copia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 14))); // NOI18N

        lblBookTitle.setBackground(new java.awt.Color(204, 204, 204));

        lblTitle.setText("Título:");

        lvlISBN.setText("ISBN:");

        lblBookISBN.setBackground(new java.awt.Color(204, 204, 204));

        lblType.setText("Tipo:");

        lblBookType.setBackground(new java.awt.Color(204, 204, 204));

        lblBookEditorial.setBackground(new java.awt.Color(204, 204, 204));

        lblEditorial.setText("Editorial:");

        lblBookEdition.setBackground(new java.awt.Color(204, 204, 204));

        lblEdition1.setText("Edición:");

        lblBookState.setBackground(new java.awt.Color(204, 204, 204));

        lblState.setText("Estado:");

        lblCopyCode.setText("Nº de Copia:");

        lblBookCopyCode.setBackground(new java.awt.Color(204, 204, 204));

        jListAuthors.setBackground(new java.awt.Color(238, 238, 238));
        jListAuthors.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autor(es)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        jListAuthors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAuthors.setToolTipText("");
        jListAuthors.setFocusable(false);
        jListAuthors.setSelectionBackground(new java.awt.Color(238, 238, 238));
        jListAuthors.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jListAuthors);

        jButtonBorrowRequest.setText("Solicitar préstamo");
        jButtonBorrowRequest.setVisible(false);
        jButtonBorrowRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrowRequestActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelCopyInfoLayout = new org.jdesktop.layout.GroupLayout(jPanelCopyInfo);
        jPanelCopyInfo.setLayout(jPanelCopyInfoLayout);
        jPanelCopyInfoLayout.setHorizontalGroup(
            jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCopyInfoLayout.createSequentialGroup()
                .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelCopyInfoLayout.createSequentialGroup()
                        .add(242, 242, 242)
                        .add(lblBookName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 205, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelCopyInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblEditorial)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lvlISBN)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblTitle)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblType)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblEdition1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelCopyInfoLayout.createSequentialGroup()
                                .add(lblBookTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(lblState)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(lblBookState, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(jButtonBorrowRequest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(49, 49, 49))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelCopyInfoLayout.createSequentialGroup()
                                .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblBookISBN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblBookType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblBookEditorial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblBookEdition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanelCopyInfoLayout.createSequentialGroup()
                                        .add(6, 6, 6)
                                        .add(jScrollPane3))
                                    .add(jPanelCopyInfoLayout.createSequentialGroup()
                                        .add(lblCopyCode)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(lblBookCopyCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanelCopyInfoLayout.setVerticalGroup(
            jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelCopyInfoLayout.createSequentialGroup()
                .add(13, 13, 13)
                .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .add(lblBookTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblState, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(lblBookState, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButtonBorrowRequest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(lvlISBN, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblBookISBN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(lblCopyCode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblBookCopyCode, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelCopyInfoLayout.createSequentialGroup()
                        .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(lblType, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(lblBookType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(lblEditorial, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(lblBookEditorial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelCopyInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblBookEdition, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblEdition1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(231, 231, 231)
                .add(lblBookName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldSearch.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldSearch.setText("Introduce tu búsqueda...");
        jTextFieldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeSearchText(evt);
            }
        });
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                doFilterSearchK(evt);
            }
        });

        bGroupFilterState.add(jRadioAll);
        jRadioAll.setSelected(true);
        jRadioAll.setText("Mostrar todos");
        jRadioAll.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jRadioAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doFilterSearch(evt);
            }
        });

        bGroupFilterState.add(jRadioStored);
        jRadioStored.setText("Filtrar prestados");
        jRadioStored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doFilterSearch(evt);
            }
        });

        bGroupFilterTAI.add(jRadioByTitle);
        jRadioByTitle.setSelected(true);
        jRadioByTitle.setText("Título");

        bGroupFilterTAI.add(jRadioByAuthor);
        jRadioByAuthor.setText("Autor");

        bGroupFilterTAI.add(jRadioByISBN);
        jRadioByISBN.setText("ISBN");
        jRadioByISBN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        org.jdesktop.layout.GroupLayout searchPanelLayout = new org.jdesktop.layout.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(searchPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelCopyInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1)
                    .add(jScrollPane1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, searchPanelLayout.createSequentialGroup()
                        .add(240, 240, 240)
                        .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(searchPanelLayout.createSequentialGroup()
                                .add(jRadioByTitle)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jRadioByAuthor)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jRadioByISBN))
                            .add(jTextFieldSearch))
                        .add(240, 240, 240))
                    .add(searchPanelLayout.createSequentialGroup()
                        .add(0, 327, Short.MAX_VALUE)
                        .add(jRadioAll)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 110, Short.MAX_VALUE)
                        .add(jRadioStored)
                        .add(0, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, searchPanelLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jTextFieldSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioByTitle)
                    .add(jRadioByAuthor)
                    .add(jRadioByISBN))
                .add(18, 18, 18)
                .add(searchPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioAll)
                    .add(jRadioStored))
                .add(69, 69, 69)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelCopyInfo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        searchPanel.setVisible(false);

        searchAndBorrow.add(searchPanel, "cardSearchPanel");

        loginPanel.setBackground(new java.awt.Color(230, 230, 230));

        jButtonBack.setText("Volver a búsqueda");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelLogin.setBackground(new java.awt.Color(222, 222, 222));

        jTextFieldUser.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        lblPWD.setText("Contraseña");
        lblPWD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUser.setText("Usuario");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldPWD.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPWD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jButtonLogin.setText("Aceptar");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        lblWrongUPWD.setForeground(new java.awt.Color(204, 0, 0));
        lblWrongUPWD.setText("Combinación de usuario y contraseña no válida");
        lblWrongUPWD.setVisible(false);

        org.jdesktop.layout.GroupLayout jPanelLoginLayout = new org.jdesktop.layout.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLoginLayout.createSequentialGroup()
                .add(jPanelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelLoginLayout.createSequentialGroup()
                        .add(230, 230, 230)
                        .add(jTextFieldUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelLoginLayout.createSequentialGroup()
                        .add(205, 205, 205)
                        .add(lblWrongUPWD))
                    .add(jPanelLoginLayout.createSequentialGroup()
                        .add(314, 314, 314)
                        .add(lblPWD))
                    .add(jPanelLoginLayout.createSequentialGroup()
                        .add(325, 325, 325)
                        .add(lblUser))
                    .add(jPanelLoginLayout.createSequentialGroup()
                        .add(230, 230, 230)
                        .add(jTextFieldPWD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelLoginLayout.createSequentialGroup()
                        .add(263, 263, 263)
                        .add(jButtonLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLoginLayout.createSequentialGroup()
                .add(48, 48, 48)
                .add(lblUser)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(lblWrongUPWD)
                .add(39, 39, 39)
                .add(lblPWD)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldPWD, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(66, 66, 66)
                .add(jButtonLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32))
        );

        jTabbedPaneLogin.addTab("                                Acceso de Miembros                                ", jPanelLogin);

        org.jdesktop.layout.GroupLayout loginPanelLayout = new org.jdesktop.layout.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(loginPanelLayout.createSequentialGroup()
                .add(loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButtonBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(loginPanelLayout.createSequentialGroup()
                        .addContainerGap(139, Short.MAX_VALUE)
                        .add(jTabbedPaneLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 719, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .add(jTabbedPaneLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 403, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 83, Short.MAX_VALUE)
                .add(jButtonBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchAndBorrow.add(loginPanel, "cardLogin");

        borrowPanel.setBackground(new java.awt.Color(230, 230, 230));

        jButtonBackFromBorrow.setText("Volver a búsqueda");
        jButtonBackFromBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout borrowPanelLayout = new org.jdesktop.layout.GroupLayout(borrowPanel);
        borrowPanel.setLayout(borrowPanelLayout);
        borrowPanelLayout.setHorizontalGroup(
            borrowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(borrowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButtonBackFromBorrow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(832, Short.MAX_VALUE))
        );
        borrowPanelLayout.setVerticalGroup(
            borrowPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, borrowPanelLayout.createSequentialGroup()
                .addContainerGap(532, Short.MAX_VALUE)
                .add(jButtonBackFromBorrow, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchAndBorrow.add(borrowPanel, "cardBorrow");

        mainJTabbedPanel.addTab("                           Búsqueda                           ", searchAndBorrow);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1007, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 575, Short.MAX_VALUE)
        );

        mainJTabbedPanel.addTab("                              Administración                              ", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainJTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainJTabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void filterByState() {
        stateCopies = new ArrayList();
        ArrayList<Copy> auxCopies2 = new ArrayList();
        if (jRadioStored.isSelected()) {
            for (int i = 0; i < listCopies.size(); i++) {
                if (listCopies.get(i).getState().equals(Copy.CopyState.STORED)) {
                    stateCopies.add(listCopies.get(i));
                }
            }
        } else {
            for (int i = 0; i < listCopies.size(); i++) {
                stateCopies.add(listCopies.get(i));
            }
        }
        modelCopies.clear();
        if (!jTextFieldSearch.getText().equals("") && !jTextFieldSearch.getText().startsWith("Introduce tu búsqueda...")) {
            auxCopies2 = filterByTAI(listCopies);
            for (int i = 0; i < auxCopies2.size(); i++) {
                modelCopies.addElement(auxCopies2.get(i));
            }
        } else {
            for (int i = 0; i < stateCopies.size(); i++) {
                modelCopies.addElement(stateCopies.get(i));
            }
        }
    }

    private ArrayList<Copy> filterByTAI(ArrayList<Copy> auxCopies) {
        ArrayList<Copy> auxCopies2 = new ArrayList();
        String auxText = jTextFieldSearch.getText().toLowerCase();
        if (jRadioByTitle.isSelected()) {
            for (int i = 0; i < auxCopies.size(); i++) {
                if (auxCopies.get(i).getBook().getTitle().toLowerCase().contains(auxText)) {
                    auxCopies2.add(auxCopies.get(i));
                }
            }
        } else if (jRadioByAuthor.isSelected()) {
            for (int i = 0; i < auxCopies.size(); i++) {
                for (int j = 0; j < auxCopies.get(i).getBook().getAuthor().size(); j++) {
                    if (auxCopies.get(i).getBook().getAuthor().get(j).getName().toLowerCase().contains(auxText) || auxCopies.get(i).getBook().getAuthor().get(j).getLastname().toLowerCase().contains(auxText)) {
                        auxCopies2.add(auxCopies.get(i));
                    }
                }
            }
        } else if (jRadioByISBN.isSelected()) {
            for (int i = 0; i < auxCopies.size(); i++) {
                if (auxCopies.get(i).getBook().getISBN().toLowerCase().startsWith(auxText)) {
                    auxCopies2.add(auxCopies.get(i));
                }
            }
        }
        return auxCopies2;
    }

    private void removeSearchText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSearchText
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (jTextFieldSearch.getText().startsWith("Introduce tu búsqueda...")) {
            jTextFieldSearch.setForeground(Color.BLACK);
            jTextFieldSearch.setText("");
        }
    }//GEN-LAST:event_removeSearchText

    private void doFilterSearch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doFilterSearch
        // TODO add your handling code here:
        filterByState();
    }//GEN-LAST:event_doFilterSearch

    private void doFilterSearchK(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doFilterSearchK
        // TODO add your handling code here:
        filterByState();
    }//GEN-LAST:event_doFilterSearchK

    private void displayItem(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_displayItem
        // TODO add your handling code here:
        Object a = jListCopies.getSelectedValue();
        if (a==null)
        {
        lblBookTitle.setText("");
        lblBookISBN.setText("");
        lblBookType.setText("");
        lblBookEditorial.setText("");
        lblBookEdition.setText("");
        lblBookState.setText("");
        lblBookCopyCode.setText("");
        modelAuthors.clear();
        jButtonBorrowRequest.setVisible(false);
        }
        else
        {
        Copy b = (Copy) (a);
        lblBookTitle.setText(b.getBook().getTitle());
        lblBookISBN.setText(b.getBook().getISBN());
        lblBookType.setText(b.getBook().getType().toString());
        lblBookEditorial.setText(b.getBook().getEditorial());
        lblBookEdition.setText(Integer.toString(b.getBook().getEdition()));
        switch (b.getState()) {
            case BORROWED:
                lblBookState.setText("Prestado");
                lblBookState.setForeground(Color.red);
                jButtonBorrowRequest.setVisible(false);
                break;
            case STORED:
                lblBookState.setText("Disponible");
                lblBookState.setForeground(Color.green);
                jButtonBorrowRequest.setVisible(true);
                break;
            default:
                throw new AssertionError();
        }
        lblBookCopyCode.setText(Integer.toString(b.getBookCode()));
        listAuthors = new ArrayList();
        for (int i = 0; i < b.getBook().getAuthor().size(); i++) {
            listAuthors.add(b.getBook().getAuthor().get(i));
        }
        modelAuthors.clear();
        for (int i = 0; i < listAuthors.size(); i++) {
            modelAuthors.addElement(listAuthors.get(i));
        }
        jListAuthors.setModel(modelAuthors);
        }
    }//GEN-LAST:event_displayItem

    private void jButtonBorrowRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrowRequestActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(searchAndBorrow.getLayout());
        if (loggedMember.getUserid()==null)
        {
        cl.show(searchAndBorrow, "cardLogin");
        }
        else
        {
        cl.show(searchAndBorrow, "cardBorrow");
        }
        destination=SwitchPanel.BORROW;
    }//GEN-LAST:event_jButtonBorrowRequestActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(searchAndBorrow.getLayout());
        cl.show(searchAndBorrow, "cardSearchPanel");
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        loggedMember=new Member();
        for (int i=0; i<listMembers.size(); i++)
        {
        if (jTextFieldUser.getText().equals(listMembers.get(i).getUserid()) && jTextFieldPWD.getText().equals(listMembers.get(i).getPwd()))
        {
        loggedMember.setPersonName(listMembers.get(i).getPersonName());
        loggedMember.setPersonLastName(listMembers.get(i).getPersonLastName());
        loggedMember.setPhone(listMembers.get(i).getPhone());
        loggedMember.setAddress(listMembers.get(i).getAddress());
        loggedMember.setMemberID(listMembers.get(i).getMemberID());
        loggedMember.setUserid(listMembers.get(i).getUserid());
        loggedMember.setPwd(listMembers.get(i).getPwd());
        break;
        }
        
        }
        System.out.println((loggedMember.getUserid()==null));
        if (loggedMember.getUserid()==null)
        {
        lblWrongUPWD.setVisible(true);
        }
        else
        {
        lblWrongUPWD.setVisible(false);
            switch (destination) {
                case BORROW:
                            CardLayout cl = (CardLayout)(searchAndBorrow.getLayout());
        cl.show(searchAndBorrow, "cardBorrow");
                    break;
                case PREFERENCES:
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        if (System.getProperty("os.name").startsWith("Mac OS")) {
            try {
                UIManager.setLookAndFeel("com.apple.laf.AquaLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(LibraryMain.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (System.getProperty("os.name").startsWith("Windows")) {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                Logger.getLogger(LibraryMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(LibraryMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGroupFilterState;
    private javax.swing.ButtonGroup bGroupFilterTAI;
    private javax.swing.JPanel borrowPanel;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBackFromBorrow;
    private javax.swing.JButton jButtonBorrowRequest;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JList jListAuthors;
    private javax.swing.JList jListCopies;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCopyInfo;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JRadioButton jRadioAll;
    private javax.swing.JRadioButton jRadioByAuthor;
    private javax.swing.JRadioButton jRadioByISBN;
    private javax.swing.JRadioButton jRadioByTitle;
    private javax.swing.JRadioButton jRadioStored;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneLogin;
    private javax.swing.JTextField jTextFieldPWD;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldUser;
    private javax.swing.JLabel lblBookCopyCode;
    private javax.swing.JLabel lblBookEdition;
    private javax.swing.JLabel lblBookEditorial;
    private javax.swing.JLabel lblBookISBN;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblBookState;
    private javax.swing.JLabel lblBookTitle;
    private javax.swing.JLabel lblBookType;
    private javax.swing.JLabel lblCopyCode;
    private javax.swing.JLabel lblEdition1;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblPWD;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblWrongUPWD;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel lvlISBN;
    private javax.swing.JTabbedPane mainJTabbedPanel;
    private javax.swing.JPanel searchAndBorrow;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
    
    ArrayList<Author> listAuthors;
    ArrayList<Copy> listCopies;
    ArrayList<Member> listMembers;
    Member loggedMember=new Member();
    ArrayList<Copy> stateCopies = new ArrayList();
    SwitchPanel destination;
    javax.swing.DefaultListModel<Copy> modelCopies = new javax.swing.DefaultListModel<>();
    javax.swing.DefaultListModel<Author> modelAuthors = new javax.swing.DefaultListModel<>();
}
